# Generated by Django 2.2.11 on 2020-03-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customtext_temp2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='temp3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
