# Generated by Django 2.2.11 on 2020-03-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customtext_csc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='temp4',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
