# Generated by Django 2.2.11 on 2020-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customtext_temp4'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='temp5',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
