# Generated by Django 2.2.11 on 2020-03-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_customtext_temp5'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='temp6',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
